services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: dlet
      POSTGRES_PASSWORD: pdletw
      POSTGRES_DB: words
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dlet -d words"]
      interval: 10s
      retries: 5
      timeout: 5s

  web:
    build: .
    container_name: flask_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://dlet:pdletw@db:5432/words
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data:
